# Generated by Django 3.2.15 on 2022-08-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220815_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='blog.post'),
        ),
    ]
